"""Sobol variance decomposition on the eight factors the Morris screen ranked highest.

Why this exists, and what it is allowed to say.

The Morris screen (`morris_screen.py`, appendix A4.6 and A5.5) ranks factors by mu*, the mean
absolute elementary effect, and reports sigma, the spread of those effects. A high sigma means
the factor's effect depends on where the other factors sit. It cannot say whether that is
interaction with another factor or curvature in the factor itself, and the appendix says so.
Three of the top eight, a[4], a[8] and omega, have sigma/mu* above one and are unresolved in
exactly that way.

Sobol decomposes the output variance instead of screening it, and separates the two:

    S_i     first order. The share of output variance removed, on average, by learning
            factor i alone. Curvature in factor i alone still shows up here.
    S_Ti    total order. The share of output variance that would remain if every factor
            except i were fixed. The gap S_Ti - S_i is interaction involving i, and nothing
            else. That gap is the number Morris could not produce.

Design. Saltelli's scheme uses two independent N-by-k samples A and B and k cross matrices.
The release design uses the next power of two above 1,000: N=1,024. The index design costs
N(k+2)=10,240 model points. An additional N=1,024 noise-replicate block makes the executed
cache 11,264 points. Estimators are Saltelli (2010) for S_i and Jansen
(1999) for S_Ti.

Scope, and this is the limitation that matters. Only the eight Morris leaders are varied. The
other 110 parameters are held at nominal. So the variance being decomposed is the variance
these eight generate between them, not the model's total variance. Every index below is
conditional on that choice, and the correct reading of "S_i = 0.4" is "forty per cent of the
variance generated by these eight factors within plus or minus twenty-five per cent". It is
not a statement about the model as a whole, and A5.5's effect shares by kind remain the right
place to look for that. Stating it otherwise would be the vacuous-robustness error the project
has already made twice.

Ranges. Plus or minus 25 per cent of nominal, matching both the OAT star and the Morris
hypercube, so the three designs are directly comparable.

Reference point. Traditions at 0.85, not 1.0, for the reason given in `morris_screen.py`: at
full adherence the governance matrix cancels exactly and a third of the model goes dark. None
of the eight factors here is a governance entry, but the reference point is kept identical so
the Sobol and Morris numbers describe the same location in parameter space.

Noise. The model is stochastic. Common random numbers are used throughout, every evaluation
running seeds 0..NSEED-1, so the same noise realisation enters every point and cancels in the
differences the estimators take. What survives inflates S_Ti and depresses S_i, both slightly.
`residual_noise()` measures it directly by evaluating the same point twice under different
seed blocks, and the result is reported alongside the indices rather than assumed away.

Uncertainty. Bootstrap over the N sample rows, 2,000 resamples, percentile intervals. An index
whose interval covers zero is unresolved, not zero.

Cached to `../research/sobol.json`; resumable, atomic saves, safe to interrupt.

Run:  python3 sobol_indices.py [n_workers] [batch]
"""
import hashlib, importlib.util, sys, os, json
import numpy as np
from concurrent.futures import ProcessPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL = os.path.join(HERE, 'aa_group_model.py')
OUT = os.path.abspath(os.path.join(HERE, '..', 'research', 'sobol.json'))

# The eight leaders of the Morris screen, in its order. See appendix A5.5.
FACTORS = ['p_gate', 'delta0', 'churn', 'het_sd', 'drop_k', 'a:4', 'a:8', 'omega']

N_BASE = 1024        # power-of-two rows in A and B; cost is N_BASE * (k + 2)
SPREAD = 0.25        # plus or minus 25 per cent of nominal, matching OAT and Morris
NSEED = 5
H = 1560
T_REF = 0.85
SEED = 20260802


def _load():
    spec = importlib.util.spec_from_file_location('m', MODEL)
    mm = importlib.util.module_from_spec(spec)
    sys.modules['m'] = mm
    spec.loader.exec_module(mm)
    return mm


def evaluate(arg):
    """arg = (x, seed_offset). x is a point in the unit hypercube, length 8."""
    x, off = arg
    mm = _load()
    P = {'a': mm.DEFAULTS['a'].copy()}
    for xi, pid in zip(x, FACTORS):
        mult = 1.0 + SPREAD * (2.0 * xi - 1.0)
        if pid.startswith('a:'):
            P['a'][int(pid.split(':')[1])] *= mult
        else:
            P[pid] = mm.DEFAULTS[pid] * mult
    T = np.full(12, T_REF)
    runs = [mm.simulate(T, P=P, seed=s + off, T_end=H) for s in range(NSEED)]
    return [float(np.mean([r['N'] for r in runs])),
            float(np.mean([r['mean'] for r in runs]))]


def design(k, n, seed=SEED):
    """A, B and the k cross matrices AB_i. Sobol' sequences would be lower discrepancy;
    a fixed-seed Latin-hypercube-free uniform draw is used because the estimators below
    assume independent rows and because reproducibility from one integer matters more here
    than the last few per cent of convergence."""
    rng = np.random.default_rng(seed)
    A = rng.random((n, k))
    B = rng.random((n, k))
    ABs = []
    for i in range(k):
        AB = A.copy()
        AB[:, i] = B[:, i]
        ABs.append(AB)
    return A, B, ABs


def _save(out):
    tmp = OUT + '.tmp'
    json.dump(out, open(tmp, 'w'))
    os.replace(tmp, OUT)


def indices(fA, fB, fAB, nboot=2000, seed=SEED):
    """Saltelli (2010) first order, Jansen (1999) total order, with a row bootstrap.

    S_i  = mean_j fB_j (fAB_ij - fA_j) / Var
    S_Ti = mean_j (fA_j - fAB_ij)^2 / (2 Var)

    Var is taken over the concatenation of fA and fB, which is the standard choice and the
    stable one when N is small.
    """
    n, k = fAB.shape
    rng = np.random.default_rng(seed)
    def _one(idx):
        a, b = fA[idx], fB[idx]
        v = np.var(np.concatenate([a, b]), ddof=1)
        if v <= 0:
            return np.full(k, np.nan), np.full(k, np.nan)
        ab = fAB[idx]
        s1 = np.mean(b[:, None] * (ab - a[:, None]), axis=0) / v
        st = np.mean((a[:, None] - ab) ** 2, axis=0) / (2.0 * v)
        return s1, st
    base_s1, base_st = _one(np.arange(n))
    bs1 = np.empty((nboot, k)); bst = np.empty((nboot, k))
    for b in range(nboot):
        idx = rng.integers(0, n, n)
        bs1[b], bst[b] = _one(idx)
    q = lambda arr: (np.nanpercentile(arr, 2.5, axis=0), np.nanpercentile(arr, 97.5, axis=0))
    lo1, hi1 = q(bs1); lot, hit = q(bst)
    return dict(S1=base_s1.tolist(), S1_lo=lo1.tolist(), S1_hi=hi1.tolist(),
                ST=base_st.tolist(), ST_lo=lot.tolist(), ST_hi=hit.tolist())


def residual_noise(out, k, n):
    """How much of S_T is Monte Carlo rather than model.

    The noise replicate set re-evaluates the A rows with a disjoint seed block. Feeding those
    as if they were AB_i for a factor that was never changed gives the total-order index the
    estimator would report for a factor with no effect at all. That number is the floor: any
    S_T at or below it is noise.
    """
    key = lambda tag, j: f'{tag}_{j}'
    have = all(key('NOISE', j) in out for j in range(n))
    if not have:
        return None
    fA = np.array([out[key('A', j)] for j in range(n)])
    fB = np.array([out[key('B', j)] for j in range(n)])
    fN = np.array([out[key('NOISE', j)] for j in range(n)])
    floors = []
    for o in (0, 1):
        v = np.var(np.concatenate([fA[:, o], fB[:, o]]), ddof=1)
        floors.append(float(np.mean((fA[:, o] - fN[:, o]) ** 2) / (2.0 * v)))
    return floors


if __name__ == '__main__':
    nw = int(sys.argv[1]) if sys.argv[1:] else 4
    batch = int(sys.argv[2]) if sys.argv[2:] else 10 ** 9
    k = len(FACTORS)
    A, B, ABs = design(k, N_BASE)

    jobs = []                       # (tag, row) -> point, seed offset
    pts = {}
    for j in range(N_BASE):
        jobs.append(('A', j)); pts[('A', j)] = (A[j], 0)
        jobs.append(('B', j)); pts[('B', j)] = (B[j], 0)
        jobs.append(('NOISE', j)); pts[('NOISE', j)] = (A[j], 1000)
    for i in range(k):
        for j in range(N_BASE):
            jobs.append((f'AB{i}', j)); pts[(f'AB{i}', j)] = (ABs[i][j], 0)

    model_hash = hashlib.sha256(open(MODEL, 'rb').read()).hexdigest()
    script_hash = hashlib.sha256(open(__file__, 'rb').read()).hexdigest()
    out = json.load(open(OUT)) if os.path.exists(OUT) else {}
    if (out.get('meta', {}).get('model_sha256') != model_hash or
            out.get('meta', {}).get('script_sha256') != script_hash):
        out = {}
    out['meta'] = dict(schema_version=2, status='incomplete', model_sha256=model_hash,
                       script_sha256=script_hash, script='model/sobol_indices.py',
                       factors=FACTORS, n_base=N_BASE, spread=SPREAD, nseed=NSEED,
                       seed_range=[0,NSEED-1], noise_seed_range=[1000,1000+NSEED-1],
                       horizon=H, dt=0.5, T_ref=T_REF, seed=SEED,
                       index_points=N_BASE*(len(FACTORS)+2), jobs_expected=len(jobs),
                       outcomes=['membership', 'mean_practice'],
                       role='screening/decomposition; five common-random-number seeds per point')

    todo = [j for j in jobs if f'{j[0]}_{j[1]}' not in out][:batch]
    print(f'{len(out)-1} of {len(jobs)} points done, running {len(todo)}', flush=True)
    if todo:
        n = 0
        with ProcessPoolExecutor(nw) as ex:
            for jb, res in zip(todo, ex.map(evaluate, [pts[j] for j in todo])):
                out[f'{jb[0]}_{jb[1]}'] = res
                n += 1
                if n % 20 == 0:
                    _save(out)
        _save(out)

    done = sum(1 for j in jobs if f'{j[0]}_{j[1]}' in out)
    out['meta']['jobs_completed'] = done
    out['meta']['status'] = 'complete' if done == len(jobs) else 'incomplete'
    print(f'{done} of {len(jobs)} complete', flush=True)
    if done == len(jobs):
        fA = np.array([out[f'A_{j}'] for j in range(N_BASE)])
        fB = np.array([out[f'B_{j}'] for j in range(N_BASE)])
        res = {}
        for o, name in enumerate(out['meta']['outcomes']):
            fAB = np.array([[out[f'AB{i}_{j}'][o] for i in range(k)] for j in range(N_BASE)])
            res[name] = indices(fA[:, o], fB[:, o], fAB)
        res['noise_floor_ST'] = residual_noise(out, k, N_BASE)
        out['result'] = res
        out['meta']['status'] = 'complete'
        _save(out)
        print('ALL DONE', flush=True)
    else:
        print('PARTIAL', flush=True)
